In [1]:
import numpy as np

In [2]:
A = np.array([[1,3]])
B = np.array([[1,-1]
              ,[6,4]])

In [3]:
A

array([[1, 3]])

In [5]:
B

array([[ 1, -1],
       [ 6,  4]])

In [6]:
np.linalg.eig(B)

(array([2.5+1.93649167j, 2.5-1.93649167j]),
 array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
        [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]]))